# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9f640e7c9fdaec8ebb675b26d235db2b15a4d3f00dc29224a726bbdd1386be6ea8bc87d5bb0aecbc0feea6a0f8746462f0391c5039b67d0bec37835005196db

test:
  secret_key_base: eaea386c2ecc1b8beee4e6230125f605020c9735e297cd836b8e2485c0c79ccaf7367443174b1619eee9ae23952b1dce85c838f4a106a0cb86c5f31fc45b103a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
